### ISSUE TITLE
強制的に終了してしまう

### ISSUE THREAD

**Issue by Yuj1** [ecobost/iRobot_cpp_interface#1]
初めまして．
大学の研究で使わせていただいております．

実行すると，プログラムが勝手に終了してしまいます．
どうすれば，解決できるでしょうか？
アドバイスお願いします．
実行したときの画面を画像で添付します．
後2つお聞きしたいのですが，↓の”////.//”は何を書けばいいのでしょうか？
また，それはどのようにすれば，分かるのでしょうか？
// Open the serial port.
    port = "////.//" + port;

![file](https://cloud.githubusercontent.com/assets/20166862/16557653/18205aa4-421c-11e6-8031-0322ac7a7143.png)

Windows8.1
Visual studio 2013 professionalを使用しています．

**Comment by ecobost** [comment]
----------日本語版の下記 (Google 翻訳で翻訳)
Hi!
I tried to use Google Translate to read your message but I do not understand exactly what you are saying. If you write me in English I could help you. You could also send me the Visual Studio errors in text so I can translate them.

Here is an example of how to use the code:
https://github.com/ecobost/iRobot_cpp_interface/blob/master/Windows/main.cpp

----------日本語版
こんにちは！
私はGoogleがあなたのメッセージを読むために翻訳を使用してみましたが、私はあなたが言っている正確に何を理解していません。あなたは英語で私を記述する場合、私はあなたを助けることができます。私はそれらを翻訳できるようにするには、テキストに私のVisual Studioエラーを送信することができます。

ここでコードを使用する方法の例を示します。
https://github.com/ecobost/iRobot_cpp_interface/blob/master/Windows/main.cpp

Greetings,

**Comment by Yuj1** [comment]
When it's carried out, a program will end immediately.
How would I be able to settle it?
Please advise.

What should be written on "////.//" of iRobot.cpp?

**Comment by ecobost** [comment]
IRobot.cpp should not be modified. The variable "port" has to be passed in line 8 of the main.cpp. The variable "port" is the name of the serial port where the Roomba is connected, you can check it by opening the Device Manager (in the Control Panel) and checking "Ports (COM & LPT)". For example, if the Roomba is connected on COM3 then you have to change line 8 in main.cpp to iRobot myiRobot("COM3");
